import type { ProductConfig } from './index'

const cateringConfig: ProductConfig = {
  product_type: 'catering',
  product_name: 'Catering',
  brand_name: 'GridMaster HQ',
  trial_days: 45,
  navigation: {
    red: [
      {
        id: 'ai_mode',
        label: 'AI Mode',
        subtext: 'Hands-free AI staff communication only',
      },
      {
        id: 'agency',
        label: 'Agency',
        subtext: 'Temp staff requests and invoices',
      },
      {
        id: 'competing_events',
        label: 'Competing Events',
        subtext: '10-week early warning on local labor competition',
      },
      {
        id: 'transport',
        label: 'Transport',
        subtext: 'Van times, carpool coordination, and route monitoring',
      },
      {
        id: 'pay_rates',
        label: 'Pay Rates',
        subtext: 'Estimated labor rates for grid costing and payroll export',
      },
      {
        id: 'user_management',
        label: 'User Management',
        subtext: 'Roles, permissions, and account access',
      },
      {
        id: 'notifications',
        label: 'Notifications',
        subtext: 'Alert preferences and quiet hours',
      },
      {
        id: 'integrations',
        label: 'Integrations',
        subtext: 'Connected tools and services',
      },
      {
        id: 'billing',
        label: 'Billing',
        subtext: 'Plan, usage, and invoice history',
      },
      {
        id: 'settings',
        label: 'Settings',
        subtext: 'Company profile, platform defaults, and portal settings',
      },
      {
        id: 'expert_mode',
        label: 'Expert Mode',
        subtext: 'Faster navigation for experienced coordinators',
      },
      { id: 'help', label: 'Help' },
    ],
    blue: [
      {
        id: 'new_event',
        label: 'New Event',
        subtext: 'Quick Event, BEO upload, or manual entry',
      },
      {
        id: 'event_settings',
        label: 'Event Settings',
        subtext: 'Defaults and preferences for new events',
      },
      {
        id: 'note_templates',
        label: 'Note Templates',
        subtext: 'Reusable coordinator notes for events',
      },
      {
        id: 'my_templates',
        label: 'My Templates',
        subtext: 'Your saved grids and past event templates',
      },
      {
        id: 'gridmaster_templates',
        label: 'GridMaster Templates',
        subtext: 'Starter templates by event type and size',
      },
      {
        id: 'ai_template_builder',
        label: 'AI Template Builder',
        subtext: 'Guided or command — built in seconds',
      },
      {
        id: 'staff',
        label: 'Staff',
        subtext: 'Your roster, profiles, and development',
      },
      {
        id: 'clients',
        label: 'Clients',
        subtext: 'Companies, contacts, and location notes',
      },
      {
        id: 'roles',
        label: 'Roles',
        subtext: 'Position types and default uniforms',
      },
      {
        id: 'uniforms',
        label: 'Uniforms',
        subtext: 'Reusable uniform presets for events',
      },
      {
        id: 'training',
        label: 'Training',
        subtext: 'Courses, progress, and certifications',
      },
      {
        id: 'reports',
        label: 'Reports',
        subtext: 'Labor, payroll, performance, and event cost reports',
      },
      {
        id: 'incentives',
        label: 'Incentives',
        subtext: 'Gift cards, recognition, and staff appreciation',
      },
      {
        id: 'expert_mode',
        label: 'Expert Mode',
        subtext: 'Faster navigation for experienced coordinators',
      },
      { id: 'help', label: 'Help' },
    ],
  },
  labels: {
    command_center: 'Command Center',
    calendar: 'Calendar',
    coordinator: 'Coordinator',
    check_in: 'check in',
    check_out: 'check out',
    times_logged: 'times logged',
    interest_list: 'Interest List',
    estimated_hours: 'Estimated Hours',
    footer_ask_ai: 'Ask GridMaster AI',
    footer_community: 'GridMaster Community',
    sign_in_heading: 'Sign in to your account',
    sign_in: 'Sign In',
    signing_in: 'Signing in...',
    email: 'Email',
    password: 'Password',
    password_reset_note:
      'Contact your GridMaster administrator to reset your password.',
    signed_in_success: 'Signed in successfully',
    error_invalid_credentials: 'Invalid email or password.',
    error_network: 'Network error. Please try again.',
    confirm: 'Confirm',
    coming_soon: 'coming soon',
    upcoming_events: 'Upcoming Events',
    needs_attention: 'Needs Attention',
    fully_staffed: 'Fully Staffed',
    month_view: 'Month',
    week_view: 'Week',
    today: 'Today',
    show_cancelled: 'Show Cancelled',
    postponed_hold: 'postponed · hold',
    previous_period: 'Previous',
    next_period: 'Next',
    this_week_and_next: 'This Week & Next',
    cc_action_items: 'Action Items',
    cc_staff_ai_inbox: 'Staff AI Inbox',
    cc_labor_overview: 'Labor Overview',
    cc_vendor_alerts: 'Vendor Alerts',
    cc_highlights: 'Highlights',
    cc_tools: 'Tools',
    cc_no_open_action_items: 'No open action items',
    cc_all_clear_subtext: 'All clear — new items will appear here',
    cc_needs_decision: 'Needs Decision',
    cc_human_required: 'Human Required',
    cc_resolved: 'Resolved',
    cc_no_events_this_week: 'No events this week',
    cc_no_vendor_alerts: 'No vendor alerts',
    cc_no_highlights_yet: 'No highlights yet',
    cc_no_competing_events_detected: 'No competing events detected',
    cc_this_week: 'This week',
    cc_open: 'open',
    cc_new: 'new',
    cc_alerts: 'alerts',
    cc_tool_competing_event_search: 'Competing Event Search',
    cc_tool_weather_query: 'Weather Query',
    cc_tool_traffic_query: 'Traffic Query',
    cc_tool_broadcast_all: 'Broadcast to All Staff',
    cc_tool_roster_health: 'Roster Health Check',
    cc_tool_availability_pulse: 'Availability Pulse Check',
    cc_gift_cards: 'Gift Cards',
    cc_view_history: 'View history',
    cc_monthly_budget: 'Monthly budget',
    cc_budget_used: '$0 used',
    cc_budget_remaining: '$— remaining',
    cc_no_gift_cards_sent:
      'No gift cards sent this month · Send your first recognition from a staff profile',
    cc_tool_competing_event_search_subtitle: 'Search by date range',
    cc_tool_traffic_query_subtitle: 'Routes by event date',
    cc_tool_roster_health_subtitle: 'Staffing completeness score',
    cc_tool_weather_query_subtitle: 'Forecast by event date',
    cc_tool_broadcast_all_subtitle: 'SMS all active staff',
    cc_tool_availability_pulse_subtitle: 'Poll staff availability',
    account_user: 'Account / User',
    my_profile: 'My Profile',
    event_mode: 'Event Mode',
    sleep_mode: 'Sleep Mode',
    log_out: 'Log Out',
    nav_section_operations: 'Operations',
    nav_section_account: 'Account',
    nav_section_preferences: 'Preferences',
    nav_section_events: 'Events',
    nav_section_templates: 'Templates',
    nav_section_people: 'People',
    nav_section_development: 'Development',
    nav_section_more: 'More',
    training: 'Training',
    es_calendar_no_events_headline:
      'No events yet. Tap + New Event to get started.',
    es_calendar_no_events_secondary:
      'Your first event takes about 2 minutes with Quick Event — or upload your BEO and our AI builds it for you instantly.',
    es_calendar_new_event_cta: '+ New Event',
    es_staff_empty_headline:
      'Your staff are being set up. Check back as your team completes their profiles.',
    es_staff_empty_secondary:
      'Need to add someone manually? Tap Staff in the left menu under People.',
    es_fill_positions_staffed_headline:
      "You're fully staffed for this event. Nice work.",
    es_cc_no_events_headline: "You're all set up. Let's put GridMaster to work.",
    es_cc_no_events_body:
      'GridMaster handles your staffing outreach, confirmations, check-ins, and real-time event management — all from here. When your first event is active, this screen becomes your operational nerve center.',
    es_cc_no_events_cta: 'Go to Calendar → Create Your First Event',
    es_cc_no_events_secondary:
      'Every action you take teaches GridMaster your preferences — the more you use it, the smarter it gets.',
    ne_mode_prompt: 'How would you like to start?',
    ne_quick_event: 'Quick Event',
    ne_quick_event_subtext: '9 fields. Done in 60 seconds.',
    ne_beo_upload: 'BEO Upload',
    ne_beo_upload_subtext: 'Drop your BEO and AI builds the event for you.',
    ne_manual_entry: 'Manual Entry',
    ne_manual_entry_subtext: 'Fill in every detail yourself.',
    ne_cancel: 'Cancel',
    ne_mode_selected: 'selected',
    overlay_discard_confirm: 'Are you sure? Your progress will be lost.',
    overlay_keep_editing: 'Keep editing',
    overlay_discard_changes: 'Discard changes',
    qe_event_name: 'Event Name',
    qe_event_name_placeholder: 'e.g. Johnson Wedding Reception',
    qe_client_name: 'Client Name',
    qe_client_name_placeholder: 'e.g. Johnson Family',
    qe_link_existing_client: 'Link to existing client',
    qe_link_existing_venue: 'Link to existing venue',
    qe_search_client_placeholder: 'Search clients...',
    qe_search_venue_placeholder: 'Search venues...',
    qe_clear_selection: 'Clear',
    qe_event_date: 'Event Date',
    qe_event_start_time: 'Event Start Time',
    qe_start_time_tbd: 'TBD',
    qe_venue: 'Venue',
    qe_venue_placeholder: 'e.g. Ritz-Carlton Ballroom',
    qe_guest_count: 'Guest Count',
    qe_guest_count_placeholder: 'e.g. 150',
    qe_event_type: 'Event Type',
    qe_select_event_type: 'Select event type...',
    qe_service_style: 'Service Style',
    qe_select_service_style: 'Select service style...',
    qe_total_staff_needed: 'Total Staff Needed',
    qe_total_staff_placeholder: 'e.g. 12',
    qe_create_event: 'Create Event',
    qe_creating: 'Creating...',
    qe_field_required: 'Required',
    form_uniform: 'Uniform',
    form_select_uniform: 'Select uniform preset...',
    form_no_uniform_presets_prefix:
      'No uniform presets saved yet — set them up in ',
    form_no_uniform_presets_suffix: '.',
    form_note_template: 'Note Template',
    form_select_note_template: 'Select note template...',
    form_no_note_templates_prefix:
      'No note templates saved yet — set them up in ',
    form_no_note_templates_suffix: '.',
    ps_event_created_heading: 'Event Created!',
    ps_add_more_details: 'Add More Details',
    ps_build_staff_grid: 'Build My Staff Grid',
    ps_done_go_to_calendar: "I'm done for now — go to calendar",
    beo_drop_zone_primary: 'Drop your BEO here',
    beo_drop_zone_secondary: 'PDF or photo — AI builds the event for you',
    beo_or_divider: 'or',
    beo_browse_files: 'Browse files',
    beo_processing_heading: 'Reading your BEO...',
    beo_processing_subtext: 'This takes about 10 seconds',
    beo_review_heading: 'We found the following details',
    beo_review_subtext: 'Review and confirm before creating the event',
    beo_notes: 'Notes',
    beo_notes_placeholder: 'Special instructions, setup notes, dietary restrictions...',
    beo_confirm_create: 'Looks good — Create Event',
    beo_start_over: 'Start over',
    beo_error_message:
      "We couldn't read this BEO. Please try a clearer photo or enter details manually.",
    beo_try_again: 'Try again',
    beo_enter_manually: 'Enter manually',
    beo_extraction_system_prompt:
      'You are a catering operations assistant. Extract event details from this Banquet Event Order. Respond only with a JSON object containing these fields: event_name, client_name, event_date (YYYY-MM-DD format), event_start_time (HH:MM 24hr format or null), venue_name, guest_count (integer or null), event_type (one of: wedding, corporate, social, gala_fundraiser, holiday_party, simple, delivery, custom), service_style (one of: plated, buffet, stations, cocktail, family_style, box_lunch, drop_off, or null if not specified), total_staff_needed (integer or null), notes (any special instructions). Only include fields you can confidently extract. Do not guess.',
    me_section_event_basics: 'Event Basics',
    me_section_venue: 'Venue',
    me_section_guest_staffing: 'Guest & Staffing',
    me_section_event_details: 'Event Details',
    me_section_save_options: 'Save Options',
    me_event_end_time: 'Event End Time',
    me_end_time_tbd: 'TBD',
    me_address: 'Address',
    me_address_placeholder: 'e.g. 123 Main St, Orlando FL',
    me_arrival_notes: 'Arrival Notes',
    me_arrival_notes_placeholder: 'Loading dock, parking info, access codes...',
    me_buffer_pct: 'Buffer %',
    me_rating_floor: 'Rating Floor',
    me_select_rating_floor: 'Select rating floor...',
    me_star: 'star',
    me_stars: 'stars',
    me_uniform_notes: 'Uniform Notes',
    me_uniform_notes_placeholder: 'Black tie, black non-slip shoes required...',
    me_coordinator_notes: 'Coordinator Notes',
    me_coordinator_notes_placeholder: 'Internal notes only — not visible to staff',
    me_bar_service_type: 'Bar Service Type',
    me_select_bar_service_type: 'Select bar service type...',
    me_bar_service_custom_placeholder:
      'e.g. Wine service only during dinner, champagne toast at 8pm',
    me_staff_notes: 'Staff Notes',
    me_staff_notes_placeholder:
      'e.g. Request bilingual staff, no staff with visible tattoos per client request, experienced wine service required',
    me_alcohol_cutoff: 'Alcohol Cutoff',
    me_vehicle_departure_time: 'Vehicle Departure Time',
    me_vehicle_load_time: 'Vehicle Load Time',
    me_searching: 'Searching...',
    me_submit_error_fallback: 'Failed to create event',
    uniforms_heading: 'Uniforms',
    uniforms_subtext:
      'Save your standard uniforms here to reuse them across events.',
    uniforms_roles_subtext_prefix:
      'Default uniforms are attached to specific roles in the staffing grid. You can change or edit the default uniform for each role in ',
    uniforms_roles_subtext_suffix:
      ', or override it per role and shift directly inside the event grid when building your staffing.',
    uniforms_add: 'Add Uniform',
    uniforms_name: 'Name',
    uniforms_name_placeholder: 'e.g. Black Tie',
    uniforms_description: 'Description',
    uniforms_description_placeholder:
      'e.g. Black tuxedo, white dress shirt, black bowtie, black non-slip shoes required',
    uniforms_save: 'Save',
    uniforms_empty_headline: 'No uniforms saved yet.',
    uniforms_empty_subtext: 'Add your first uniform preset to use it across events.',
    uniforms_field_required: 'Required',
    uniforms_delete_confirm: 'Delete this uniform preset?',
    uniforms_load_error: 'Failed to load uniforms',
    uniforms_save_error: 'Failed to save uniform',
    uniforms_delete_error: 'Failed to delete uniform',
    note_templates_heading: 'Note Templates',
    note_templates_subtext:
      'Save reusable coordinator notes to apply across events.',
    note_templates_usage_subtext:
      'Note templates are used in the Coordinator Notes field when creating events.',
    note_templates_add: 'Add Template',
    note_templates_name: 'Name',
    note_templates_name_placeholder: 'e.g. Standard Wedding Protocol',
    note_templates_event_type: 'Event Type',
    note_templates_all_event_types: 'All event types',
    note_templates_description: 'Description',
    note_templates_description_placeholder:
      'e.g. Remind captain to confirm bar closing time with client 30 min before cutoff...',
    note_templates_save: 'Save',
    note_templates_empty_headline: 'No note templates saved yet.',
    note_templates_empty_subtext:
      'Add your first template to reuse coordinator notes across events.',
    note_templates_field_required: 'Required',
    note_templates_delete_confirm: 'Delete this note template?',
    note_templates_load_error: 'Failed to load note templates',
    note_templates_save_error: 'Failed to save note template',
    note_templates_delete_error: 'Failed to delete note template',
    roles_page_heading: 'Roles',
    roles_page_subtext_prefix:
      'Define your role types and assign default uniforms. To build and manage your uniform presets, go to ',
    roles_page_subtext_suffix: '.',
    roles_add: 'Add Role',
    roles_name: 'Role Name',
    roles_name_placeholder: 'e.g. Server',
    roles_default_uniform: 'Default Uniform',
    roles_select_uniform: 'Select a uniform preset...',
    roles_uniform_custom: 'Custom',
    roles_no_uniform: 'No uniform assigned',
    roles_custom_uniform: 'Custom Uniform Text',
    roles_custom_uniform_placeholder:
      'Optional — use when no preset applies or to override',
    roles_save: 'Save',
    roles_empty_headline: 'No roles saved yet.',
    roles_empty_subtext: 'Add your first role to define types and default uniforms.',
    roles_field_required: 'Required',
    roles_delete_confirm: 'Delete this role?',
    roles_load_error: 'Failed to load roles',
    roles_save_error: 'Failed to save role',
    roles_delete_error: 'Failed to delete role',
  },
  colors: {
    brand_navy: '#1B3A5C',
    brand_red: '#C0392B',
    status_green: '#22C55E',
    status_amber: '#F59E0B',
    status_red: '#EF4444',
    status_blue: '#3B82F6',
    brand_light_blue: '#D5E8F0',
    brand_mid_blue: '#2E75B6',
    text_body: '#444444',
    text_muted: '#6b7280',
    surface_hover: '#EEF2F7',
    white: '#FFFFFF',
  },
  features: {
    ai_grid_generation: true,
    beo_upload: true,
    competing_events: true,
    captain_portal: true,
    sms_relay: true,
    expert_mode: true,
    rating_system: true,
    temp_agency: true,
    invoice_reconciliation: true,
    incentives: true,
    transport: true,
  },
  roles: [
    'server',
    'bartender',
    'bar_back',
    'food_runner',
    'captain',
    'setup_crew',
    'breakdown_crew',
    'line_cook',
    'prep_cook',
    'dishwasher',
    'kitchen_runner',
    'driver',
  ],
  event_types: [
    { value: 'wedding', label: 'Wedding', color: '#C9A84C' },
    { value: 'corporate', label: 'Corporate', color: '#1B3A5C' },
    { value: 'social', label: 'Social Celebrations', color: '#7B5EA7' },
    { value: 'gala_fundraiser', label: 'Gala & Fundraiser', color: '#2E8B57' },
    {
      value: 'holiday_party',
      label: 'Holiday Party',
      color: '#C0392B',
      second_color: '#2E8B57',
    },
    { value: 'simple', label: 'Simple', color: '#008080' },
    { value: 'delivery', label: 'Delivery', color: '#1B3A5C' },
    { value: 'custom', label: 'Custom', color: '#C85000' },
  ],
  service_styles: [
    { value: 'plated', label: 'Plated' },
    { value: 'buffet', label: 'Buffet' },
    { value: 'stations', label: 'Stations' },
    { value: 'cocktail', label: 'Cocktail' },
    { value: 'family_style', label: 'Family Style' },
    { value: 'box_lunch', label: 'Box Lunch' },
    { value: 'drop_off', label: 'Drop Off' },
  ],
  bar_service_types: [
    { value: 'full_bar', label: 'Full Bar' },
    { value: 'beer_wine', label: 'Beer & Wine' },
    { value: 'soft_drinks', label: 'Soft Drinks Only' },
    { value: 'no_bar', label: 'No Bar' },
    { value: 'custom', label: 'Custom' },
  ],
  grid_departments: ['FOH', 'BOH', 'Setup/Breakdown', 'Other'],
  buffer_options: [0, 5, 10, 15, 20],
  rating_floors: [1, 2, 3, 4],
  default_buffer_pct: 10,
  default_alcohol_cutoff: false,
}

export default cateringConfig
