import type { ProductConfig } from './index'

const cateringConfig: ProductConfig = {
  product_type: 'catering',
  product_name: 'Catering',
  brand_name: 'GridMaster HQ',
  trial_days: 45,
  navigation: {
    red: [
      { id: 'ai_mode', label: 'AI Mode' },
      { id: 'settings', label: 'Settings' },
      { id: 'user_management', label: 'User Management' },
      { id: 'notifications', label: 'Notifications' },
      { id: 'agency', label: 'Agency' },
      { id: 'competing_events', label: 'Competing Events' },
      { id: 'pay_rates', label: 'Pay Rates' },
      { id: 'transport', label: 'Transport' },
      { id: 'integrations', label: 'Integrations' },
      { id: 'expert_mode', label: 'Expert Mode' },
      { id: 'help', label: 'Help' },
    ],
    blue: [
      { id: 'new_event', label: 'New Event' },
      { id: 'event_settings', label: 'Event Settings' },
      { id: 'staff', label: 'Staff' },
      { id: 'clients', label: 'Clients' },
      { id: 'roles', label: 'Roles' },
      { id: 'templates', label: 'Templates' },
      { id: 'reports', label: 'Reports' },
      { id: 'incentives', label: 'Incentives' },
      { id: 'expert_mode', label: 'Expert Mode' },
      { id: 'help', label: 'Help' },
    ],
  },
  labels: {
    command_center: 'Command Center',
    calendar: 'Calendar',
    coordinator: 'Coordinator',
    check_in: 'check in',
    check_out: 'check out',
    times_logged: 'times logged',
    interest_list: 'Interest List',
    estimated_hours: 'Estimated Hours',
    footer_ask_ai: 'Ask GridMaster AI',
    footer_community: 'GridMaster Community',
    sign_in_heading: 'Sign in to your account',
    sign_in: 'Sign In',
    signing_in: 'Signing in...',
    email: 'Email',
    password: 'Password',
    password_reset_note:
      'Contact your GridMaster administrator to reset your password.',
    signed_in_success: 'Signed in successfully',
    error_invalid_credentials: 'Invalid email or password.',
    error_network: 'Network error. Please try again.',
    confirm: 'Confirm',
    coming_soon: 'coming soon',
    upcoming_events: 'Upcoming Events',
    needs_attention: 'Needs Attention',
    fully_staffed: 'Fully Staffed',
    month_view: 'Month',
    week_view: 'Week',
    today: 'Today',
    show_cancelled: 'Show Cancelled',
    postponed_hold: 'postponed · hold',
    previous_period: 'Previous',
    next_period: 'Next',
    this_week_and_next: 'This Week & Next',
  },
  colors: {
    brand_navy: '#1B3A5C',
    brand_red: '#C0392B',
    status_green: '#22C55E',
    status_amber: '#F59E0B',
    status_red: '#EF4444',
    status_blue: '#3B82F6',
    brand_light_blue: '#D5E8F0',
    brand_mid_blue: '#2E75B6',
    text_body: '#444444',
  },
  features: {
    ai_grid_generation: true,
    beo_upload: true,
    competing_events: true,
    captain_portal: true,
    sms_relay: true,
    expert_mode: true,
    rating_system: true,
    temp_agency: true,
    invoice_reconciliation: true,
    incentives: true,
    transport: true,
  },
  roles: [
    'server',
    'bartender',
    'bar_back',
    'food_runner',
    'captain',
    'setup_crew',
    'breakdown_crew',
    'line_cook',
    'prep_cook',
    'dishwasher',
    'kitchen_runner',
    'driver',
  ],
  event_types: [
    { value: 'wedding_life', label: 'Wedding & Life Events', color: '#C9A84C' },
    { value: 'corporate', label: 'Corporate', color: '#1B3A5C' },
    { value: 'social', label: 'Social Celebrations', color: '#7B5EA7' },
    { value: 'gala_fundraiser', label: 'Gala & Fundraiser', color: '#2E8B57' },
    { value: 'simple_delivery', label: 'Simple / Delivery', color: '#008080' },
    { value: 'custom', label: 'Custom', color: '#C85000' },
    { value: 'past_cancelled', label: 'Past / Cancelled', color: '#9E9E9E' },
  ],
  grid_departments: ['FOH', 'BOH', 'Setup/Breakdown', 'Other'],
  buffer_options: [0, 5, 10, 15, 20],
  rating_floors: [1, 2, 3, 4],
}

export default cateringConfig
