export type ProductType = 'catering' | 'vending' | 'gigs' | 'venues' | 'services'

export interface NavItem {
  id: string
  label: string
  subtext?: string
}

export interface ProductNavigation {
  red: NavItem[]
  blue: NavItem[]
}

export interface ProductLabels {
  command_center: string
  calendar: string
  coordinator: string
  check_in: string
  check_out: string
  times_logged: string
  interest_list: string
  estimated_hours: string
  footer_ask_ai: string
  footer_community: string
  sign_in_heading: string
  sign_in: string
  signing_in: string
  email: string
  password: string
  password_reset_note: string
  signed_in_success: string
  error_invalid_credentials: string
  error_network: string
  confirm: string
  coming_soon: string
  upcoming_events: string
  needs_attention: string
  fully_staffed: string
  month_view: string
  week_view: string
  today: string
  show_cancelled: string
  postponed_hold: string
  previous_period: string
  next_period: string
  this_week_and_next: string
  cc_action_items: string
  cc_staff_ai_inbox: string
  cc_labor_overview: string
  cc_vendor_alerts: string
  cc_highlights: string
  cc_tools: string
  cc_no_open_action_items: string
  cc_all_clear_subtext: string
  cc_needs_decision: string
  cc_human_required: string
  cc_resolved: string
  cc_no_events_this_week: string
  cc_no_vendor_alerts: string
  cc_no_highlights_yet: string
  cc_no_competing_events_detected: string
  cc_this_week: string
  cc_open: string
  cc_new: string
  cc_alerts: string
  cc_tool_competing_event_search: string
  cc_tool_weather_query: string
  cc_tool_traffic_query: string
  cc_tool_broadcast_all: string
  cc_tool_roster_health: string
  cc_tool_availability_pulse: string
  cc_gift_cards: string
  cc_view_history: string
  cc_monthly_budget: string
  cc_budget_used: string
  cc_budget_remaining: string
  cc_no_gift_cards_sent: string
  cc_tool_competing_event_search_subtitle: string
  cc_tool_traffic_query_subtitle: string
  cc_tool_roster_health_subtitle: string
  cc_tool_weather_query_subtitle: string
  cc_tool_broadcast_all_subtitle: string
  cc_tool_availability_pulse_subtitle: string
  account_user: string
  my_profile: string
  event_mode: string
  sleep_mode: string
  log_out: string
  nav_section_operations: string
  nav_section_account: string
  nav_section_preferences: string
  nav_section_events: string
  nav_section_templates: string
  nav_section_people: string
  nav_section_development: string
  nav_section_more: string
  training: string
  es_calendar_no_events_headline: string
  es_calendar_no_events_secondary: string
  es_calendar_new_event_cta: string
  es_staff_empty_headline: string
  es_staff_empty_secondary: string
  es_fill_positions_staffed_headline: string
  es_cc_no_events_headline: string
  es_cc_no_events_body: string
  es_cc_no_events_cta: string
  es_cc_no_events_secondary: string
  ne_mode_prompt: string
  ne_quick_event: string
  ne_quick_event_subtext: string
  ne_beo_upload: string
  ne_beo_upload_subtext: string
  ne_manual_entry: string
  ne_manual_entry_subtext: string
  ne_cancel: string
  ne_mode_selected: string
  overlay_discard_confirm: string
  overlay_keep_editing: string
  overlay_discard_changes: string
  qe_event_name: string
  qe_event_name_placeholder: string
  qe_client_name: string
  qe_client_name_placeholder: string
  qe_link_existing_client: string
  qe_link_existing_venue: string
  qe_search_client_placeholder: string
  qe_search_venue_placeholder: string
  qe_clear_selection: string
  qe_event_date: string
  qe_event_start_time: string
  qe_start_time_tbd: string
  qe_venue: string
  qe_venue_placeholder: string
  qe_guest_count: string
  qe_guest_count_placeholder: string
  qe_event_type: string
  qe_select_event_type: string
  qe_service_style: string
  qe_select_service_style: string
  qe_total_staff_needed: string
  qe_total_staff_placeholder: string
  qe_create_event: string
  qe_creating: string
  qe_field_required: string
  form_uniform: string
  form_select_uniform: string
  form_no_uniform_presets_prefix: string
  form_no_uniform_presets_suffix: string
  form_note_template: string
  form_select_note_template: string
  form_no_note_templates_prefix: string
  form_no_note_templates_suffix: string
  ps_event_created_heading: string
  ps_add_more_details: string
  ps_build_staff_grid: string
  ps_done_go_to_calendar: string
  beo_drop_zone_primary: string
  beo_drop_zone_secondary: string
  beo_or_divider: string
  beo_browse_files: string
  beo_processing_heading: string
  beo_processing_subtext: string
  beo_review_heading: string
  beo_review_subtext: string
  beo_notes: string
  beo_notes_placeholder: string
  beo_confirm_create: string
  beo_start_over: string
  beo_error_message: string
  beo_try_again: string
  beo_enter_manually: string
  beo_extraction_system_prompt: string
  me_section_event_basics: string
  me_section_venue: string
  me_section_guest_staffing: string
  me_section_event_details: string
  me_section_save_options: string
  me_event_end_time: string
  me_end_time_tbd: string
  me_address: string
  me_address_placeholder: string
  me_arrival_notes: string
  me_arrival_notes_placeholder: string
  me_buffer_pct: string
  me_rating_floor: string
  me_select_rating_floor: string
  me_star: string
  me_stars: string
  me_uniform_notes: string
  me_uniform_notes_placeholder: string
  me_coordinator_notes: string
  me_coordinator_notes_placeholder: string
  me_bar_service_type: string
  me_select_bar_service_type: string
  me_bar_service_custom_placeholder: string
  me_staff_notes: string
  me_staff_notes_placeholder: string
  me_alcohol_cutoff: string
  me_vehicle_departure_time: string
  me_vehicle_load_time: string
  me_searching: string
  me_submit_error_fallback: string
  uniforms_heading: string
  uniforms_subtext: string
  uniforms_roles_subtext_prefix: string
  uniforms_roles_subtext_suffix: string
  uniforms_add: string
  uniforms_name: string
  uniforms_name_placeholder: string
  uniforms_description: string
  uniforms_description_placeholder: string
  uniforms_save: string
  uniforms_empty_headline: string
  uniforms_empty_subtext: string
  uniforms_field_required: string
  uniforms_delete_confirm: string
  uniforms_load_error: string
  uniforms_save_error: string
  uniforms_delete_error: string
  note_templates_heading: string
  note_templates_subtext: string
  note_templates_usage_subtext: string
  note_templates_add: string
  note_templates_name: string
  note_templates_name_placeholder: string
  note_templates_event_type: string
  note_templates_all_event_types: string
  note_templates_description: string
  note_templates_description_placeholder: string
  note_templates_save: string
  note_templates_empty_headline: string
  note_templates_empty_subtext: string
  note_templates_field_required: string
  note_templates_delete_confirm: string
  note_templates_load_error: string
  note_templates_save_error: string
  note_templates_delete_error: string
  roles_page_heading: string
  roles_page_subtext_prefix: string
  roles_page_subtext_suffix: string
  roles_add: string
  roles_name: string
  roles_name_placeholder: string
  roles_default_uniform: string
  roles_select_uniform: string
  roles_uniform_custom: string
  roles_no_uniform: string
  roles_custom_uniform: string
  roles_custom_uniform_placeholder: string
  roles_save: string
  roles_empty_headline: string
  roles_empty_subtext: string
  roles_field_required: string
  roles_delete_confirm: string
  roles_load_error: string
  roles_save_error: string
  roles_delete_error: string
}

export interface ProductColors {
  brand_navy: string
  brand_red: string
  status_green: string
  status_amber: string
  status_red: string
  status_blue: string
  brand_light_blue: string
  brand_mid_blue: string
  text_body: string
  text_muted: string
  surface_hover: string
  white: string
}

export interface ProductFeatures {
  ai_grid_generation: boolean
  beo_upload: boolean
  competing_events: boolean
  captain_portal: boolean
  sms_relay: boolean
  expert_mode: boolean
  rating_system: boolean
  temp_agency: boolean
  invoice_reconciliation: boolean
  incentives: boolean
  transport: boolean
}

export interface EventType {
  value: string
  label: string
  color: string
  second_color?: string
}

export interface ServiceStyleOption {
  value: string
  label: string
}

export interface BarServiceTypeOption {
  value: string
  label: string
}

export interface ProductConfig {
  product_type: ProductType
  product_name: string
  brand_name: string
  trial_days: number
  navigation: ProductNavigation
  labels: ProductLabels
  colors: ProductColors
  features: ProductFeatures
  roles: string[]
  event_types: EventType[]
  service_styles: ServiceStyleOption[]
  bar_service_types: BarServiceTypeOption[]
  grid_departments: string[]
  buffer_options: number[]
  rating_floors: number[]
  default_buffer_pct: number
  default_alcohol_cutoff: boolean
}

export { default } from './catering.config'
